### ISSUE TITLE
Fatal error: TypeError: this.expectationResultFactory is not a function

### ISSUE THREAD

**Issue by derickbailey** [onury/grunt-jasmine-nodejs#40]
I'm updating a project from older versions of this library, older grunt, etc. to the latest and greatest of everything.

I'm not running into this error / stack trace at the end of my spec execution:

```
Fatal error: TypeError: this.expectationResultFactory is not a function
  at Suite.onException (/Users/derickbailey/dev/projects/rabbus/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2219:48)
  at QueueRunner.queueRunnerFactory.onException (/Users/derickbailey/dev/projects/rabbus/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2330:28)
  at onException (/Users/derickbailey/dev/projects/rabbus/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1924:12)
  at [object Object]._onTimeout (/Users/derickbailey/dev/projects/rabbus/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1910:11)
  at Timer.listOnTimeout (timers.js:92:15)
```

this error has been reported in the jasmine project, here: https://github.com/jasmine/jasmine/issues/1147

have you run into this issue? did i miss something when updating grunt and this library, etc?

**Comment by onury** [comment]
No I didn't. First look at your stack, I don't think it's related with this plugin; but jasmine-core. 
Have you tried running your specs directly with jasmine? Is the result same?

I've subscribed to the issue. Let me know if you have new info. I'll help if I can.
